config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root "home#index"
  get "home", to: "home#index", as: "home"

  get "unimplemented", to: "static_pages#unimplemented"

  resources :announcements, only: [ :show ]

  resources :fanclubs, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :subscriptions, only: [ :create, :destroy ]
    member do
      get :subscribers
    end
  end
  resources :subscriptions, only: [ :index ]

  resources :contents, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  get "my_contents", to: "contents#my_contents", as: :my_contents

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :fanclub

  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: true
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    before_action :authenticate_user!, except: [ :show, :index ]
    before_action :set_content, only: [ :edit, :update, :destroy ]

    def index
      @contents = Content.order(created_at: :asc)
    end

    def my_contents
      @contents = current_user.contents

      if @contents.nil?
        flash[:alert] = "コンテンツが見つかりませんでした。"
        redirect_back(fallback_location: root_path) and return
        nil
      end
    end

    def show
      @content = Content.find_by(id: params[:id])
      unless @content
        redirect_to root_path, alert: "コンテンツが見つかりませんでした。"
      end

      @fanclub = @content.fanclub
      @contents = @fanclub.contents
    end

    def new
      unless current_user.fanclub.present?
        flash[:alert] = "ファンクラブが見つかりません。"
        redirect_back(fallback_location: root_path) and return
      end

      @fanclub = current_user.fanclub
      @content = @fanclub.contents.build
    end

    def create
      @fanclub = current_user.fanclub
      @content = @fanclub.contents.build(content_params)
      if @content.save
        redirect_to fanclub_path(@fanclub), notice: "コンテンツが投稿されました"
      else
        render :new
      end
    end

    def edit
      @content = Content.find_by(id: params[:id])
    end

    def update
      if @content.fanclub.user != current_user
        redirect_to root_path, alert: "自分のコンテンツだけ編集できます" and return
      end

      if @content.update(content_params)
        redirect_to content _path, notice: "更新しました。"
      else
        flash.now[:alert] = "更新に失敗しました。"
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @content.fanclub.user == current_user
        @content.destroy
        redirect_to my_contents_path, notice: "コンテンツを削除しました"
      else
        redirect_to root_path, alert: "自分のコンテンツだけ削除できます"
      end
    end

    private

    def set_content
      @content = Content.find_by(id: params[:id])
      if @content.nil?
        redirect_to root_path, alert: "コンテンツが見つかりませんでした。" and return
      end
    end

    def content_params
      params.require(:content).permit(:title, :description, :image)
    end
end

app/views/contents/edit.html.erb
<div class="flex-wrapper w-full my-7">
  <div class="content-wrapper w-1/3">
    <%= form_with model: @content, local: true do |form| %>
      <h2 class="text-3xl font-semibold text-center text-gray-800 mb-3">コンテンツの編集</h2>
      <div class="mt-5 mb-5 text-red-800">
        <%= render "devise/shared/error_messages", resource: @content %>
      </div>
      <%= render(CommonFormFieldComponent.new(form: form, field_name: :title, field_type: :text_field, options: { autocomplete: "title" })) %>
      <%= render(CommonFormFieldComponent.new(form: form, field_name: :description, field_type: :text_area, options: { autocomplete: "description", class: "h-40" })) %>
      <div class="mb-5">
        <%= form.label :image, "画像" %>
        <%= form.file_field :image, autocomplete: "image", class: "w-full py-2 border border-gray-300 rounded-lg" %>
        <% if @content.image.attached? %>
          <div class="mt-3">
            <%= image_tag @content.image, class: "mx-auto max-w-[300px] h-auto" %>
          </div>
        <% else %>
          <div class="mt-3 text-gray-500">現在、画像は添付されていません。</div>
        <% end %>
      </div>
      <div class="actions mt-10">
        <%= form.submit "更新", class: "w-full py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contents/index.html.erb
<div class="container mx-auto mt-5 mb-8 w-2/3">
  <h1 class="text-2xl font-bold mb-6">すべてのコンテンツ</h1>
  <div class="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 gap-6">
    <% @contents.each do |content| %>
      <%= link_to content_path(content), class: "bg-white rounded-lg shadow-md overflow-hidden cursor-pointer hover:bg-white hover:opacity-70" do %>
        <%= image_tag content.image, class: "w-full h-48 object-cover" %>
        <div class="p-4">
          <h2 class="text-lg font-bold mb-2 truncate" title="<%= content.title %>"><%= content.title %></h2>
          <p class="text-gray-600 text-sm line-clamp-2" title="<%= content.description %>"><%= content.description %></p>
          <div class="flex items-center mt-4">
            <% if content.fanclub.user.profile_image.attached? %>
              <%= image_tag content.fanclub.user.profile_image.variant(resize_to_fill: [32, 32]), 
                            class: "w-8 h-8 rounded-full mr-2" %>
            <% else %>
              <div class="w-8 h-8 bg-gray-300 rounded-full mr-2"></div>
            <% end %>
            <p class="text-sm font-medium text-gray-800"><%= content.fanclub.user.name %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/contents/my_contents.html.erb
<div class="flex-wrapper w-3/4 m-auto my-7">
  <div class="content-wrapper p-3">
    <p class="text-xl mb-1">投稿</p>
    <div class="space-y-4">
      <% @contents.each do |content| %>
        <div class="flex items-start shadow-lg rounded-lg relative">
          <%= link_to edit_content_path(content), class: "flex p-4 space-x-4 hover:bg-gray-50 hover:opacity-95" do %>
            <div class="w-32 h-32 bg-gray-300 rounded-lg overflow-hidden">
              <%= image_tag content.image.variant(resize_to_fill: [120, 120]), class: "w-full h-full object-cover" %>
            </div>
            <div class="flex-1">
              <h3 class="text-lg font-semibold"><%= content.title %></h3>
              <p class="text-sm mt-2 w-[95%]"><%= content.description %></p>
            </div>
          <% end %>
          <div class="absolute top-2 right-2">
            <%= link_to content_path(content), method: :delete, data: { turbo_method: :delete }, class: "text-red-500 hover:text-red-700" do %>
              <%= heroicon "trash", options: { class: "mx-auto w-6 h-6" } %> 削除
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<div class="flex-wrapper w-full">
  <div class="content-wrapper w-1/3">
    <%= form_with model: @content, local: true do |form| %>
      <h2 class="text-3xl font-semibold text-center text-gray-800 mb-3">新しいコンテンツ</h2>
      <div class="mt-5 mb-5 text-red-800">
        <%= render "devise/shared/error_messages", resource: @content %>
      </div>
      <%= render(CommonFormFieldComponent.new(form: form, field_name: :title, field_type: :text_field, options: { autocomplete: "title" })) %>
      <%= render(CommonFormFieldComponent.new(form: form, field_name: :description, field_type: :text_area, options: { autocomplete: "description", class: "h-40" })) %>
      <%= render(CommonFormFieldComponent.new(form: form, field_name: :image, field_type: :file_field, options: { autocomplete: "image" })) %>
      <div class="actions mt-10">
        <%= form.submit "投稿", class: "w-full py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contents/show.html.erb
<div class="flex-wrapper w-full mb-5 bg-white border-b border-gray-300">
  <div class="flex w-2/3 p-5 space-x-2 items-center justify-center">
    <div class="text-center">
      <%= link_to fanclub_path(@fanclub), class: "hover:text-blue-400 hover:underline" do %>
        <% if @fanclub.user&.profile_image&.attached? %>
          <%= image_tag @fanclub.user.profile_image, class: "block mx-auto m-0 rounded-[50%] w-[150px] h-[150px]" %>
        <% else %>
          <%= image_tag "noimage.jpg", class: "block mx-auto m-0 rounded-[50%] w-[150px] h-[150px]" %>
        <% end %>
        <h2 class="text-lg font-semibold mb-2"><%= @fanclub.title %></h2>
      <% end %>
      <% if current_user %>
        <% subscription = current_user.subscriptions.find_by(fanclub: @fanclub) %>
        <% if subscription && subscription.active? %>
          <%= link_to "退会する", fanclub_subscription_path(@fanclub, subscription), data: { turbo_method: :delete }, class: "block mt-4 bg-pink-500 text-white py-4 rounded-lg hover:bg-pink-600" %>
        <% else %>
          <%= link_to "ファンになる", fanclub_subscriptions_path(@fanclub), data: { turbo_method: :post }, class: "block mt-4 bg-pink-500 text-white py-4 rounded-lg hover:bg-pink-600" %>
        <% end %>
      <% end %>
    </div>
    <div class="w-2/3">
      <p class="text-gray-700"><%= @fanclub.description %></p>
    </div>
  </div>
</div>
<div class="flex w-9/12 m-auto items-start">
  <div class="flex-wrapper w-3/5 mr-5">
    <div class="content-wrapper p-7">
      <p class="text-2xl font-bold mb-3"><%= @content.title %></p>
      <%= image_tag @content.image.variant(resize_to_fill: [200, 150]), class: "max-w-[500px] max-h-[500px]" %>
      <p class="text-sm p-1"><%= @content.description %></p>
    </div>
  </div>
  <div class="flex-wrapper w-2/5">
    <div class="content-wrapper p-3 w-full" >
      <p class="text-xl mb-1">最近の投稿</p>
      <div class="grid grid-cols-2 gap-2" >
        <% @contents.limit(5).each do |content| %>
          <%= link_to content_path(content), class: "relative w-full h-52 bg-gray-200 rounded-lg overflow-hidden cursor-pointer hover:bg-white hover:opacity-95" do %>
            <%= render 'shared/content_image', image: content.image, title: content.title, max_width: '300px' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>