config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root "home#index"
  get "home", to: "home#index", as: "home"

  get "unimplemented", to: "static_pages#unimplemented"

  resources :announcements, only: [ :show ]

  resources :fanclubs, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :subscriptions, only: [ :create, :destroy ]
    member do
      get :subscribers
    end
  end
  resources :subscriptions, only: [ :index ]

  resources :contents, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  get "my_contents", to: "contents#my_contents", as: :my_contents

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_content_image.html.erb
<% width ||= '300px' %>
<div class="relative flex justify-center">
  <%= image_tag image, class: "w-[#{width}]" %>
</div>
<div class="absolute bottom-0 bg-white opacity-50 flex w-full">
  <p class="text-sm p-1"><%= title %></p>
</div>

app/views/shared/_dropdown_menu.html.erb
<div class="list-group-item relative group">
  <div class="flex justify-between items-center">
    <button type="button" class="inline-flex w-full cursor-pointer">
      <%= button_text %>
    </button>
    <%= heroicon "chevron-right", options: { class: "ml-2" } %>
  </div>
  <div class="hidden group-hover:block absolute top-0 left-[95%] w-56 rounded-md shadow-lg bg-white ring-1 ring-gray-300 ring-opacity-5 focus:outline-none">
    <div class="py-1">
      <% menu_items.each do |item| %>
        <%= link_to item[:text], item[:url], class: "block px-4 py-2 text-sm text-gray-700 hover:bg-blue-50 hover:text-blue-400" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_fanclub_menu.html.erb
<div class="relative group">
  <%= render partial: "shared/icon_card", locals: { 
        icon_name: "home", 
        description: "ファンクラブ", 
        link: "#", 
        method: :get 
    } %>
  <div class="hidden text-black w-[190px] group-hover:block absolute w-56 rounded-md shadow-lg bg-white ring-1 ring-gray-200 ring-opacity-5 z-10">
    <%= link_to fanclub_path(current_user.fanclub), class: "block flex items-center space-x-2 list-group-item" do %>
      <p>ファンクラブページへ</p>
    <% end %>
    <%= link_to edit_fanclub_path(current_user.fanclub), class: "block flex items-center space-x-2 list-group-item" do %>
      <p>ファンクラブページを編集</p>
    <% end %>
    <div class="block h-[1px] bg-gray-200 my-3"></div>
    <div class="p-3 font-bold">
      <span class="text-pink-500">つくる (投稿)</span>
    </div>
    <%= link_to new_content_path, class: "block flex items-center space-x-2 list-group-item" do %>
      <p>新規追加</p>
    <% end %>
    <%= link_to my_contents_path, class: "block flex items-center space-x-2 list-group-item" do %>
      <p>一覧表示</p>
    <% end %>
    <div class="block h-[1px] bg-gray-200 my-3"></div>
    <div class="p-3 font-bold">
      <span class="text-pink-500">ファンとコミュニティ</span>
    </div>
    <%= link_to subscribers_fanclub_path(current_user.fanclub), class: "block flex items-center space-x-2 list-group-item" do %>
      <p>ファン一覧</p>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash-message w-full p-4 text-center text-sm text-green-700 bg-green-200 rounded-lg" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash-message w-full p-4 text-center text-sm text-red-700 bg-red-200 rounded-lg" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white py-8 border-t border-gray-200 text-gray-600">
  <div class="container mx-auto px-4 sm:px-8 lg:px-20 flex flex-col md:flex-row justify-center items-start gap-8">
    <div class="flex-2 text-center md:text-left">
      <h3 class="text-lg font-bold mb-4 pb-2 border-b border-gray-200">サイトについて</h3>
      <%= link_to root_path do %>
        <%= image_tag('logo.svg', alt: 'App Logo', class: "mx-auto md:mx-0 w-28") %>
      <% end %>
      <p class="mt-4 text-sm leading-relaxed">
        このサイトは、ファンクラブの管理やコンテンツの公開をサポートするプラットフォームです。
        ユーザーはファンクラブに参加し、お気に入りのクリエイターを応援できます。
      </p>
    </div>

    <div class="flex-1 text-center md:text-left">
      <h3 class="text-lg font-bold mb-4">ランキング</h3>
      <ul>
        <li class="mb-2">
          <%= link_to "人気のファンクラブ", fanclubs_path, class: "text-gray-500 hover:text-gray-600" %>
        </li>
        <li class="mb-2">
          <%= link_to "人気の投稿", contents_path, class: "text-gray-500 hover:text-gray-600" %>
        </li>
      </ul>
    </div>

    <div class="flex-1 text-center md:text-left">
      <h3 class="text-lg font-bold mb-4">Language</h3>
      <ul>
        <li class="mb-2">
          <%= link_to "日本語", "#", class: "text-gray-500 hover:text-gray-600" %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="shadow-md border-b border-gray-200">
  <div class="container mx-auto py-3 px-4 sm:px-8 lg:px-20 flex flex-wrap lg:flex-nowrap justify-between items-center">
    <nav class="flex flex-wrap items-center space-x-4">
      <%= link_to root_path do %>
        <%= image_tag('logo.svg', alt: 'App Logo', width: '150') %>
      <% end %>
      <%= render partial: "shared/icon_card", locals: { 
                icon_name: "fire",
                description: "ランキング", 
                link: fanclubs_path,
                method: :get
            } %>
    </nav>
    <nav class="flex flex-wrap items-center space-x-2 sm:space-x-4 mt-4 lg:mt-0">
      <% if user_signed_in? %>
        <% if current_user.fanclub&.persisted? %>
          <%= render "shared/fanclub_menu" %>
        <% else %>
          <%= render partial: "shared/icon_card", locals: { 
                    icon_name: "home", 
                    description: "ファンクラブ開設", 
                    link: new_fanclub_path,
                    method: :get 
                } %>
        <% end %>
        <%= render partial: "shared/icon_card", locals: { 
                    icon_name: "face-smile",
                    description: "アカウント", 
                    link: edit_user_registration_path,
                    method: :get
                } %>
        <%= render partial: "shared/icon_card", locals: { 
                    icon_name: "user-minus",
                    description: "ログアウト", 
                    link: destroy_user_session_path,
                    method: :delete
                } %>
      <% else %>
        <%= render partial: "shared/icon_card", locals: { 
                    icon_name: "user-plus",
                    description: "ユーザー登録", 
                    link: new_user_registration_path ,
                    method: :get
                } %>
        <%= render partial: "shared/icon_card", locals: { 
                    icon_name: "check",
                    description: "ログイン", 
                    link: new_user_session_path,
                    method: :get
                } %>
      <% end %>
    </nav>
  </div>
</header>

app/views/shared/_icon_card.html.erb
<%= link_to link, { data: { turbo_method: method }, class: "block mx-3" } do %>
  <div class="overflow-hidden cursor-pointer hover:text-blue-400">
    <!-- アイコンを表示 -->
    <div class="flex items-center justify-center">
      <%= heroicon icon_name %>
    </div>
    <!-- ラベルを表示 -->
    <p class="text-xs"><%= description %></p>
  </div>
<% end %>